### PR TITLE
nanoPb update local fork

### PR DESCRIPTION
**Pull request by jlecuyer**
* Almost 4 month worth of bug fix
* 0.4.1 to 0.4.3

NOTE: No not merge before firmware release 1.2.1 is built !!!

### CODE REVIEW

**Comment by ajasmin** [comment]
I would merge the tag 0.4.3 instead of HEAD which is a few commits pass the release. See: setting version to 0.4.4-dev.

Did we even made any changes to this repo? If not, a fast forward merge may be preferable.

**Comment by gabpaquin** [comment]
@jlecuyer should we go ahead with this PR?

**Comment by jlecuyer** [comment]
@gabpaquin  there are two other bug-fix release, i'll point to 0.4.5 instead of  0.4.3

**Comment by jlecuyer** [comment]
there was no conflict, did a fast-forward

**Pull request merged**
